---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-tideproject-k8s-v1alpha1-plan
  failurePolicy: Fail
  name: vplan-v1alpha1.kb.io
  rules:
  - apiGroups:
    - tideproject.k8s
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - plans
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-tideproject-k8s-v1alpha1-project
  failurePolicy: Fail
  name: vproject-v1alpha1.kb.io
  rules:
  - apiGroups:
    - tideproject.k8s
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - projects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-tideproject-k8s-v1alpha1-wave
  failurePolicy: Fail
  name: vwave-v1alpha1.kb.io
  rules:
  - apiGroups:
    - tideproject.k8s
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - waves
  sideEffects: None
