---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tideproject.k8s
  resources:
  - milestones
  - phases
  - plans
  - projects
  - tasks
  - waves
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tideproject.k8s
  resources:
  - milestones/finalizers
  - phases/finalizers
  - plans/finalizers
  - projects/finalizers
  - tasks/finalizers
  - waves/finalizers
  verbs:
  - update
- apiGroups:
  - tideproject.k8s
  resources:
  - milestones/status
  - phases/status
  - plans/status
  - projects/status
  - tasks/status
  - waves/status
  verbs:
  - get
  - patch
  - update
