apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tide.fullname" . }}-phase-admin-role
  labels:
  {{- include "tide.labels" . | nindent 4 }}
rules:
- apiGroups:
  - tideproject.k8s
  resources:
  - phases
  verbs:
  - '*'
- apiGroups:
  - tideproject.k8s
  resources:
  - phases/status
  verbs:
  - get