apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tide.fullname" . }}-task-viewer-role
  labels:
  {{- include "tide.labels" . | nindent 4 }}
rules:
- apiGroups:
  - tideproject.k8s
  resources:
  - tasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tideproject.k8s
  resources:
  - tasks/status
  verbs:
  - get