apiVersion: v1
kind: Service
metadata:
  name: {{ include "tide.fullname" . }}-webhook-service
  labels:
  {{- include "tide.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    app.kubernetes.io/name: tide
    control-plane: controller-manager
    {{- include "tide.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.webhookService.ports | toYaml | nindent 2 }}